# Generated by Django 4.1.7 on 2023-11-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('file', models.FileField(upload_to='firevideos/')),
                ('percentage', models.FloatField(default=0.0)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
